// <auto-generated />
using System;
using LibraryManager.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryManager.Migrations
{
    [DbContext(typeof(LibraryManagerContext))]
    [Migration("20220303190553_AddMoreSeed")]
    partial class AddMoreSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryManager.Database.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookImageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookImageId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "J. K. Rowling",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 525, DateTimeKind.Local).AddTicks(8566),
                            Description = "The second instalment of boy wizard Harry Potter's adventures at Hogwarts School of Witchcraft and Wizardry, based on the novel by JK Rowling. A mysterious elf tells Harry to expect trouble during his second year at Hogwarts, but nothing can prepare him for trees that fight back, flying cars, spiders that talk and deadly warnings written in blood on the walls of the school.",
                            Genre = "Fantasy Fiction",
                            IsDeleted = false,
                            Quantity = 10,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "James Clear",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 528, DateTimeKind.Local).AddTicks(1818),
                            Description = "An atomic habit is a regular practice or routine that is not only small and easy to do but is also the source of incredible power; a component of the system of compound growth. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change.",
                            Genre = "Self improvement",
                            IsDeleted = false,
                            Quantity = 5,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mario Puzo",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 528, DateTimeKind.Local).AddTicks(1894),
                            Description = "The Godfather is a crime novel written by Mario Puzo, originally published in 1969 by G. P. Putnam's Sons. It details the story of a fictitious Sicilian Mafia family based in New York City and headed by Don Vito Corleone, who became synonymous with the Italian Mafia.",
                            Genre = "Thriller",
                            IsDeleted = false,
                            Quantity = 5,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Robert Kiyosaki",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 528, DateTimeKind.Local).AddTicks(1901),
                            Description = "Rich Dad Poor Dad is about Robert Kiyosaki (author) and his two dads—his real father (poor dad) and the father of his best friend (rich dad)—and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you do not need to earn a high income to become rich.",
                            Genre = "Personal finance",
                            IsDeleted = false,
                            Quantity = 100,
                            Title = "Rich Dad Poor Dad"
                        });
                });

            modelBuilder.Entity("LibraryManager.Database.Models.BookImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("BookImage");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.BorrowedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SendWarning")
                        .HasColumnType("bit");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.ConfirmEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmEmails");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserImageId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "0d415448-33a9-4e8b-9038-b3fabb27ee8a",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 529, DateTimeKind.Local).AddTicks(2025),
                            Email = "admin@admin.com",
                            IsDeleted = false,
                            IsLoggedIn = false,
                            Name = "Admin",
                            Password = "$MYHASH$V1$10000$WnjGq+UwNAO7PC8CGkd7EirIZEvU7sz7EXqY1jEbp296+r2o",
                            Role = "Admin",
                            Surname = "Admin"
                        },
                        new
                        {
                            Id = "417bbb60-6858-4928-962d-dd7b812a8b6b",
                            CreatedOn = new DateTime(2022, 3, 3, 21, 5, 53, 536, DateTimeKind.Local).AddTicks(8752),
                            Email = "student@student.com",
                            IsDeleted = false,
                            IsLoggedIn = false,
                            Name = "Student",
                            Password = "$MYHASH$V1$10000$165K0giMmoZIhbudf6LMINT2wUT8JzJy+tX++4xywas5VVJw",
                            Role = "Student",
                            Surname = "Student"
                        });
                });

            modelBuilder.Entity("LibraryManager.Database.Models.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("UserImage");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.Book", b =>
                {
                    b.HasOne("LibraryManager.Database.Models.BookImage", "BookImage")
                        .WithMany()
                        .HasForeignKey("BookImageId");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.BorrowedBook", b =>
                {
                    b.HasOne("LibraryManager.Database.Models.Book", "Book")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManager.Database.Models.User", "User")
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.ConfirmEmail", b =>
                {
                    b.HasOne("LibraryManager.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LibraryManager.Database.Models.User", b =>
                {
                    b.HasOne("LibraryManager.Database.Models.UserImage", "UserImage")
                        .WithMany()
                        .HasForeignKey("UserImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
